# -*- coding: utf-8 -*-
"""MyColorVision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERjejNQxMdA9wQc00eBwaIguESGhgNEK
"""

import torch
print(f"CUDA Available: {torch.cuda.is_available()}")
print(f"Device Name: {torch.cuda.get_device_name(0)}")

from ultralytics import YOLO

model = YOLO("yolo11s.pt")

model.train(
    data="/content/ninodemo/data.yaml",
    epochs=25,
    batch=32,
    imgsz=640,
    optimizer="AdamW",
    lr0=0.001,
    patience=4,
    amp=True,
    cos_lr=True,
    device=0,
    workers=2
)

metrics = model.val()


result = model("/content/ninodemo/test/images/images-24_jpg.rf.08a6d5be00abb4d254ed02738abc5b81.jpg")
result[0].show()

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.predict(
    source=0,      # cámara
    show=True
)

!cp -r /content/drive/MyDrive/ninodemo /content/ninodemo

import torch
from ultralytics import YOLO

model = YOLO("yolo11s.pt")

model.train(
    data="/content/ninodemo/data.yaml",
    epochs=100,
    batch=32,
    imgsz=640,
    optimizer="AdamW",
    weight_decay=0.0012,
    lr0=0.0004,
    patience=20,
    amp=True,
    cos_lr=True,
)

metrics = model.val()

result = model("/content/ninodemo/test/images/f7cd2093e531c63f216c6fa18770c995_jpg.rf.56e86f98da68df56c0e226d5514a479c.jpg")  # <- inferencia en el mismo device
result[0].show()

!pip install numpy

!nvidia-smi

!pip install torch

#import torch
#print(f"CUDA Available: {torch.cuda.is_available()}")
#print(f"Device Name: {torch.cuda.get_device_name(0)}")

!pip install ultralytics

!pip install roboflow