# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efVq0d6d863LYP5iKXSX0EXZtjVVn0Aw
"""

!pip install onnx onnx2tf tensorflow==2.19.0

import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("best.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph("tf_model")

import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("saved_model")
converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()

with open("model.tflite", "wb") as f:
    f.write(tflite_model)

from ultralytics import YOLO

model = YOLO("best.onnx")
model.export(format="tflite", imgsz=640)

from google.colab import files
files.download("best.tflite")

from ultralytics import YOLO

model = YOLO("best.pt")
model.export(format="tflite", imgsz=640)